apply plugin: 'maven-publish'
apply plugin: 'signing'

def sonatypeRepositoryURL
def mavenLocalFlag = hasProperty('mavenLocal') ? mavenLocal.toBoolean() : true
def timestampMsg = " at " + getDate()
if (isReleaseBuild()) {
    println 'PROCESSING MAVEN ' + (mavenLocalFlag ? 'LOCAL' : 'REMOTE') + ' RELEASE BUILD VERSION ' + project.VERSION_NAME + timestampMsg + '...'
    sonatypeRepositoryURL = hasProperty('RELEASE_REPOSITORY_URL') ? RELEASE_REPOSITORY_URL
            : "https://oss.sonatype.org/service/local/staging/deploy/maven2/"
} else {
    println 'PROCESSING MAVEN ' + (mavenLocalFlag ? 'LOCAL' : 'REMOTE') + ' SNAPSHOT BUILD VERSION ' + project.VERSION_NAME + timestampMsg + '...'
    sonatypeRepositoryURL = hasProperty('SNAPSHOT_REPOSITORY_URL') ? SNAPSHOT_REPOSITORY_URL
            : "https://oss.sonatype.org/content/repositories/snapshots/"

}

def getRepositoryPassword() {
    return hasProperty('sonatypePassword') ? sonatypePassword : ""
}

def getRepositoryUsername() {
    return hasProperty('sonatypeUsername') ? sonatypeUsername : ""
}

afterEvaluate { project ->
    task androidJavadocs(type: Javadoc) {
        source = android.sourceSets.main.java.srcDirs
        classpath += files(android.getBootClasspath().join(File.pathSeparator))
        failOnError false
    }

    task androidJavadocsJar(type: Jar, dependsOn: androidJavadocs) {
        archiveClassifier.set('javadoc')
    }

    task androidSourcesJar(type: Jar) {
        archiveClassifier.set('sources')
        from android.sourceSets.main.java.srcDirs
    }

    publishing {
        repositories {
            if (mavenLocalFlag) {
                maven {
                    name = "local"
                    url = mavenLocal().url
                }
            } else {
                maven {
                    name = "sonatype"
                    url = sonatypeRepositoryURL
                    credentials {
                        username = getRepositoryUsername()
                        password = getRepositoryPassword()
                    }
                }
            }
        }

        publications.withType(MavenPublication).configureEach { publication ->
            artifact(androidSourcesJar)
            artifact(androidJavadocsJar)
            pom {
                name = POM_SETTING_NAME
                packaging = POM_SETTING_PACKAGING
                description = POM_SETTING_DESCRIPTION
                url = POM_SETTING_URL

                scm {
                    url = POM_SETTING_SCM_URL
                    connection = POM_SETTING_SCM_CONNECTION
                    developerConnection = POM_SETTING_SCM_DEV_CONNECTION
                }

                licenses {
                    license {
                        name = POM_SETTING_LICENCE_NAME
                        url = POM_SETTING_LICENCE_URL
                        distribution = POM_SETTING_LICENCE_DIST
                    }
                }

                developers {
                    developer {
                        id = POM_SETTING_DEVELOPER_ID
                        name = POM_SETTING_DEVELOPER_NAME
                    }
                }
            }
        }
    }

    signing {
        required {
            isReleaseBuild() && gradle.taskGraph.allTasks.any { it.name.toLowerCase().startsWith("publish") }
        }
        sign publishing.publications
    }

    def stagingExtension = project.extensions.findByName("nexusStaging")
    if (stagingExtension != null) {
        nexusStaging {
            username getRepositoryUsername()
            password getRepositoryPassword()
        }
    } else if (rootProject.extensions.findByName("nexusStaging") != null) {
        rootProject.nexusStaging {
            username getRepositoryUsername()
            password getRepositoryPassword()
        }
    }
}

def getDate() {
    return new Date().format('yyyy-MM-dd HH:mm:ss')
}
